In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from tqdm import tqdm

In [6]:
train = pd.get_dummies(pd.read_csv('train.csv'), prefix_sep="__").fillna(0)
test = pd.get_dummies(pd.read_csv('test.csv'), prefix_sep="__", )

In [7]:
cat_dummies = [col for col in train 
               if "__" in col]

for col in cat_dummies:
    if col not in test.columns:
        print("Adding missing feature {}".format(col))
        test[col] = 0

test = test.reindex(train.columns, axis=1).drop(['SalePrice'], axis=1).fillna(0)

Adding missing feature Utilities__NoSeWa
Adding missing feature Condition2__RRAe
Adding missing feature Condition2__RRAn
Adding missing feature Condition2__RRNn
Adding missing feature HouseStyle__2.5Fin
Adding missing feature RoofMatl__ClyTile
Adding missing feature RoofMatl__Membran
Adding missing feature RoofMatl__Metal
Adding missing feature RoofMatl__Roll
Adding missing feature Exterior1st__ImStucc
Adding missing feature Exterior1st__Stone
Adding missing feature Exterior2nd__Other
Adding missing feature Heating__Floor
Adding missing feature Heating__OthW
Adding missing feature Electrical__Mix
Adding missing feature GarageQual__Ex
Adding missing feature PoolQC__Fa
Adding missing feature MiscFeature__TenC


In [8]:
train.sample(5)

Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
798    799          60        104.0    13518            9            5   
228    229          20         70.0     8521            5            5   
163    164          45         55.0     5500            4            6   
1314  1315          20         60.0     8190            4            6   
993    994          60         68.0     8846            6            5   

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1           ...            \
798        2008          2009       860.0           0           ...             
228        1967          1967         0.0         842           ...             
163        1956          1956         0.0           0           ...             
1314       1954          1954         0.0         732           ...             
993        2005          2006         0.0           0           ...             

      SaleType__ConLw  SaleType__New  SaleType__Oth  SaleType__WD  \
798                 0              1              0             0   
228                 0              0              0             1   
163                 0              0              0             1   
1314                0              0              0             1   
993                 0              1              0             0   

      SaleCondition__Abnorml  SaleCondition__AdjLand  SaleCondition__Alloca  \
798                        0                       0                      0   
228                        0                       0                      0   
163                        0                       0                      0   
1314                       0                       0                      0   
993                        0                       0                      0   

      SaleCondition__Family  SaleCondition__Normal  SaleCondition__Partial  
798                       0                      0                       1  
228                       0                      1                       0  
163                       0                      1                       0  
1314                      0                      1                       0  
993                       0                      0                       1  

[5 rows x 290 columns]

In [9]:
test.sample(5)

Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
1354  2815          30          0.0    17529            5            5   
1426  2887          30         50.0     7288            5            6   
118   1579          85         82.0    11105            5            5   
862   2323          80         65.0    16219            7            5   
1240  2701          60          0.0     9019            6            5   

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1           ...            \
1354       1924          1950        65.0         0.0           ...             
1426       1942          1950         0.0       305.0           ...             
118        1996          1996         0.0       870.0           ...             
862        2004          2005         0.0       779.0           ...             
1240       1994          1994         0.0       274.0           ...             

      SaleType__ConLw  SaleType__New  SaleType__Oth  SaleType__WD  \
1354                0              0              0             1   
1426                0              0              0             1   
118                 0              0              0             1   
862                 0              0              0             1   
1240                0              0              0             1   

      SaleCondition__Abnorml  SaleCondition__AdjLand  SaleCondition__Alloca  \
1354                       0                       0                      0   
1426                       0                       1                      0   
118                        0                       0                      0   
862                        0                       0                      0   
1240                       0                       0                      0   

      SaleCondition__Family  SaleCondition__Normal  SaleCondition__Partial  
1354                      0                      1                       0  
1426                      0                      0                       0  
118                       0                      1                       0  
862                       0                      1                       0  
1240                      0                      1                       0  

[5 rows x 289 columns]

In [10]:
# X_train = np.asarray(train[['LotArea', 'LotFrontage']]).astype(np.float32)
# y_train = np.asarray(train['SalePrice']).astype(np.float32)

#x_values = [i for i in range(11*2)]
X_train = np.array(np.asarray(train.drop(['SalePrice'], axis=1)), dtype=np.float32)

#y_values = [2*i + 1 for i in range(11)]
y_train = np.array(np.asarray(train['SalePrice'].fillna(0)), dtype=np.float32)


In [12]:
X_train.shape

(1460, 289)

In [13]:
y_train.shape

(1460,)

In [142]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [167]:
reg = RandomForestRegressor(max_depth=200, n_estimators=5000, n_jobs=-1)
reg.fit(X_train, y_train)


0.9815120940855117

In [ ]:
reg.score(X_train, y_train)

In [168]:
cross_val_score(reg, X_train, y_train, cv=3)

array([0.88695021, 0.85065336, 0.82462337])

In [164]:
# output = train.copy()
# output['SalePrice_pred'] = reg.predict(output.drop(['SalePrice'], axis=1))
# output[['SalePrice', 'SalePrice_pred']].sample(15)

In [169]:
output = test.copy()

output['SalePrice'] = reg.predict(output)
output[['Id', 'SalePrice']].to_csv('my_submission.csv', index=False)

In [292]:
import torch.nn as nn
import torch.nn.functional as F
import torch

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(289, 144)
        self.fc2 = nn.Linear(144, 72)
        self.fc3 = nn.Linear(72, 36)
        self.fc4 = nn.Linear(36, 18)
        self.fc5 = nn.Linear(18, 1)

    def forward(self, x):
        x = (self.fc1(x))
        x = (self.fc2(x))
        x = (self.fc3(x))
        x = (self.fc4(x))
        x = (self.fc5(x))
        return x
    


In [299]:
net = Net()
net(torch.from_numpy(X_train))

tensor([[-41.2136],
        [-38.0575],
        [-46.4659],
        ...,
        [-58.9491],
        [-45.7229],
        [-46.5732]], grad_fn=<AddmmBackward>)

In [294]:
import torch.optim as optim


# optimizer = optim.Adam(net.parameters(), lr=0.01)
# loss_function = nn.MSELoss()

loss_function = torch.nn.MSELoss() 
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)



In [295]:
X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)

# scale units
X_max, _ = torch.max(X_train_tensor, 0)
y_max, _ = torch.max(y_train_tensor, 0)

X_train_norm = torch.div(X_train_tensor, X_max)
y_train_norm = torch.div(y_train_tensor, y_max)

y_train_norm

tensor([0.2762, 0.2404, 0.2960,  ..., 0.3530, 0.1882, 0.1954])

In [296]:
BATCH_SIZE = 5
EPOCHS = 50

for epoch in range(EPOCHS):
    for i in tqdm(range(0, len(X_train_norm), BATCH_SIZE)): # from 0, to the len of x, stepping BATCH_SIZE at a time. [:50] ..for now just to dev
        batch_X = (X_train_norm[i:i+BATCH_SIZE]).view(-1, 1, 289)
        batch_y = (y_train_norm[i:i+BATCH_SIZE])

        net.zero_grad()
        
        outputs = net(batch_X)
        loss = loss_function(outputs, batch_y)
        loss.backward()
        optimizer.step()    # Does the update
        
    print('epoch {}, loss {}'.format(epoch, loss.item()))


 29%|██▉       | 86/292 [00:00<00:00, 854.50it/s]

epoch 0, loss 0.004516032990068197


 29%|██▉       | 86/292 [00:00<00:00, 859.89it/s]

epoch 1, loss 0.004474537447094917


 26%|██▋       | 77/292 [00:00<00:00, 769.26it/s]

epoch 2, loss 0.004439873155206442


 31%|███       | 91/292 [00:00<00:00, 904.55it/s]

epoch 3, loss 0.004408007953315973


 29%|██▉       | 85/292 [00:00<00:00, 846.99it/s]

epoch 4, loss 0.004377728793770075


 30%|███       | 88/292 [00:00<00:00, 874.19it/s]

epoch 5, loss 0.004348851274698973


 20%|█▉        | 57/292 [00:00<00:00, 569.49it/s]

epoch 6, loss 0.00432150112465024


 62%|██████▏   | 182/292 [00:00<00:00, 896.18it/s]

epoch 7, loss 0.004295828752219677


 12%|█▏        | 35/292 [00:00<00:00, 348.01it/s]

epoch 8, loss 0.004271920304745436


 18%|█▊        | 52/292 [00:00<00:00, 519.74it/s]

epoch 9, loss 0.004249796736985445


 26%|██▋       | 77/292 [00:00<00:00, 750.16it/s]

epoch 10, loss 0.004229415208101273


 21%|██        | 61/292 [00:00<00:00, 603.17it/s]

epoch 11, loss 0.004210697021335363


 18%|█▊        | 53/292 [00:00<00:00, 526.87it/s]

epoch 12, loss 0.004193537402898073


 32%|███▏      | 92/292 [00:00<00:00, 916.65it/s]

epoch 13, loss 0.004177824594080448


 20%|█▉        | 58/292 [00:00<00:00, 574.50it/s]

epoch 14, loss 0.0041634393855929375


 28%|██▊       | 83/292 [00:00<00:00, 826.66it/s]

epoch 15, loss 0.0041502695530653


 19%|█▉        | 55/292 [00:00<00:00, 541.12it/s]

epoch 16, loss 0.004138204734772444


 20%|██        | 59/292 [00:00<00:00, 583.78it/s]

epoch 17, loss 0.00412714621052146


 26%|██▋       | 77/292 [00:00<00:00, 334.07it/s]

epoch 18, loss 0.004116999451071024


 64%|██████▍   | 187/292 [00:00<00:00, 907.57it/s]

epoch 19, loss 0.004107680171728134


 26%|██▋       | 77/292 [00:00<00:00, 767.82it/s]

epoch 20, loss 0.0040991115383803844


 17%|█▋        | 49/292 [00:00<00:00, 484.66it/s]

epoch 21, loss 0.004091224167495966


 32%|███▏      | 93/292 [00:00<00:00, 929.89it/s]

epoch 22, loss 0.004083954729139805


 23%|██▎       | 68/292 [00:00<00:00, 679.52it/s]

epoch 23, loss 0.004077245946973562


 21%|██        | 62/292 [00:00<00:00, 611.82it/s]

epoch 24, loss 0.0040710498578846455


 25%|██▍       | 72/292 [00:00<00:00, 718.05it/s]

epoch 25, loss 0.004065319895744324


 25%|██▌       | 74/292 [00:00<00:00, 734.53it/s]

epoch 26, loss 0.004060013685375452


 29%|██▉       | 84/292 [00:00<00:00, 838.06it/s]

epoch 27, loss 0.004055094439536333


 25%|██▌       | 73/292 [00:00<00:00, 725.32it/s]

epoch 28, loss 0.00405053049325943


 29%|██▉       | 86/292 [00:00<00:00, 857.33it/s]

epoch 29, loss 0.004046291578561068


 61%|██████▏   | 179/292 [00:00<00:00, 872.91it/s]

epoch 30, loss 0.004042347893118858


 29%|██▉       | 86/292 [00:00<00:00, 855.07it/s]

epoch 31, loss 0.004038678016513586


 34%|███▎      | 98/292 [00:00<00:00, 974.31it/s]

epoch 32, loss 0.004035259131342173


 25%|██▌       | 73/292 [00:00<00:00, 723.06it/s]

epoch 33, loss 0.004032070282846689


 30%|███       | 88/292 [00:00<00:00, 870.64it/s]

epoch 34, loss 0.004029094707220793


 23%|██▎       | 66/292 [00:00<00:00, 655.43it/s]

epoch 35, loss 0.004026313778012991


 20%|██        | 59/292 [00:00<00:00, 586.42it/s]

epoch 36, loss 0.004023714456707239


 25%|██▍       | 72/292 [00:00<00:00, 708.99it/s]

epoch 37, loss 0.004021282307803631


 27%|██▋       | 78/292 [00:00<00:00, 779.30it/s]

epoch 38, loss 0.004019003827124834


 32%|███▏      | 92/292 [00:00<00:00, 911.43it/s]

epoch 39, loss 0.004016870632767677


 24%|██▍       | 71/292 [00:00<00:00, 703.92it/s]

epoch 40, loss 0.004014869686216116


 26%|██▌       | 76/292 [00:00<00:00, 710.30it/s]

epoch 41, loss 0.004012993071228266


 33%|███▎      | 97/292 [00:00<00:00, 965.37it/s]

epoch 42, loss 0.004011231474578381


 23%|██▎       | 67/292 [00:00<00:00, 662.56it/s]

epoch 43, loss 0.004009576514363289


 29%|██▉       | 85/292 [00:00<00:00, 847.35it/s]

epoch 44, loss 0.004008021671324968


 29%|██▉       | 86/292 [00:00<00:00, 859.19it/s]

epoch 45, loss 0.004006558563560247


 25%|██▌       | 74/292 [00:00<00:00, 736.36it/s]

epoch 46, loss 0.004005183931440115


 23%|██▎       | 67/292 [00:00<00:00, 664.42it/s]

epoch 47, loss 0.004003890790045261


 27%|██▋       | 78/292 [00:00<00:00, 777.14it/s]

epoch 48, loss 0.004002673085778952


100%|██████████| 292/292 [00:00<00:00, 784.91it/s]

epoch 49, loss 0.004001527093350887


In [300]:
X_test_tensor = torch.from_numpy(np.asarray(test, dtype=np.float32))
X_test_norm = torch.div(X_test_tensor, X_max)

yHat = net(X_test_norm)
yHat

tensor([[0.1049],
        [0.1122],
        [0.0972],
        ...,
        [0.1027],
        [0.0819],
        [0.0710]], grad_fn=<AddmmBackward>)

In [301]:
torch.mul(yHat, y_max)

tensor([[79223.8438],
        [84727.7734],
        [73371.7812],
        ...,
        [77505.0000],
        [61857.6016],
        [53626.7695]], grad_fn=<MulBackward0>)

In [302]:
output = test.copy()

output['SalePrice'] = torch.mul(yHat, y_max).detach().numpy()
output[['Id', 'SalePrice']].to_csv('my_submission_nn.csv', index=False)

In [303]:
output[['Id', 'SalePrice']].head(10)

Id     SalePrice
0  1461  79223.843750
1  1462  84727.773438
2  1463  73371.781250
3  1464  80335.687500
4  1465  89928.632812
5  1466  69237.492188
6  1467  73931.835938
7  1468  78886.625000
8  1469  72698.445312
9  1470  79032.671875